### ISSUE TITLE
Does it work with Speedport W724 Typ B and Raspi3 ?

### ISSUE THREAD

**Issue by MarcusCaepio** [hobbyquaker/check_speedport#1]
Hey :) 
I would like to monitor my Speedport with a Raspi3.
Do you know if this would work with your plugin?

Thanks in advance

**Comment by hobbyquaker** [comment]
I don't know if it works with the W724, I only tested it against a W921 - so you have to try it out :) You can use it on Pi3, no problem. I suggest to use https://github.com/tj/n to install a recent version of Node.js on Raspbian.

**Comment by MarcusCaepio** [comment]
Hi, tried it today and unfortunatels it does not work. But I don't know why. The status page is the same, but I always get "undefined" for all values. Would be nice, if we both can try to solve this?
